In [9]:
import pandas as pd
data = pd.read_csv('/Users/muhammadzuamaalamin/Documents/percobaancvd/datasetfix/heart_disease_new_dataset1.csv')
data

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_VEGRES1,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1,CVD_LABEL
0,1.0,1.0,b'01192021',b'01',b'19',b'2021',1100.0,b'2021000001',2.021000e+09,1.0,...,1.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
1,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000002',2.021000e+09,1.0,...,1.0,100.0,128.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,CHD Only
2,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000003',2.021000e+09,1.0,...,1.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,CHD Only
3,1.0,1.0,b'01172021',b'01',b'17',b'2021',1100.0,b'2021000004',2.021000e+09,1.0,...,1.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
4,1.0,1.0,b'01152021',b'01',b'15',b'2021',1100.0,b'2021000005',2.021000e+09,1.0,...,1.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,MI + Stroke
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,78.0,12.0,b'01062022',b'01',b'06',b'2022',1100.0,b'2021001381',2.021001e+09,NaN,...,1.0,157.0,393.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
438689,78.0,12.0,b'01122022',b'01',b'12',b'2022',1100.0,b'2021001382',2.021001e+09,NaN,...,1.0,200.0,157.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
438690,78.0,12.0,b'12212021',b'12',b'21',b'2021',1100.0,b'2021001383',2.021001e+09,NaN,...,1.0,200.0,143.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
438691,78.0,12.0,b'01112022',b'01',b'11',b'2022',1100.0,b'2021001384',2.021001e+09,NaN,...,1.0,100.0,156.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt
438692,78.0,12.0,b'12222021',b'12',b'22',b'2021',1100.0,b'2021001385',2.021001e+09,NaN,...,1.0,34.0,66.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,Healt

In [10]:
data.isnull().sum()

_STATE       0
FMONTH       0
IDATE        0
IMONTH       0
IDAY         0
            ..
_FRT16A      0
_VEG23A      0
_FRUITE1     0
_VEGETE1     0
CVD_LABEL    0
Length: 304, dtype: int64

In [11]:
data['CVD_LABEL'].value_counts()

CVD_LABEL
Healt                391852
Stroke Only           11518
CHD Only              11048
Heart Attack Only     10295
MI + CHD               8285
MI + Stroke            2137
All Three              2114
CHD + Stroke           1444
Name: count, dtype: int64

In [12]:
miss = data.isnull().mean().sort_values(ascending=False) * 100
miss

HAVECFS      100.000000
WORKCFS      100.000000
TOLDCFS      100.000000
COLGHOUS      99.993162
COLGSEX       99.993162
                ...
_TOTINDA       0.000000
_HCVU652       0.000000
_HLTHPLN       0.000000
_MENT14D       0.000000
CVD_LABEL      0.000000
Length: 304, dtype: float64

In [13]:
high = (miss >= 25).sum()
high

165

In [14]:
# Hapus kolom dengan missing value >= 50%
threshold = 25
cols_to_drop = miss[miss > threshold].index
data1 = data.drop(columns=cols_to_drop)

print(f"Kolom yang dihapus ({len(cols_to_drop)}): {list(cols_to_drop)}")
print(f"Shape sebelum: {data.shape}")
print(f"Shape sesudah: {data1.shape}")

Kolom yang dihapus (165): ['HAVECFS', 'WORKCFS', 'TOLDCFS', 'COLGHOUS', 'COLGSEX', 'SIGMTES1', 'MEDSHEPB', 'TRETHEPC', 'PRIRHEPC', 'HAVEHEPC', 'VCLNTES1', 'SDNATES1', 'BLDSTFIT', 'CSRVCTL2', 'LASTSIG4', 'PCSTALK', 'PCPSARS2', 'PSATIME1', 'STOLTEST', 'CCLGHOUS', 'CDHELP', 'STOOLDN1', 'VIRCOLO1', 'SMALSTOL', 'PSATEST1', 'HPVADSHT', 'CSRVINST', 'LOADULK2', 'CDDISCUS', 'CDSOCIAL', 'CDASSIST', 'CDHOUSE', 'CSRVCLIN', 'CSRVDEIN', 'CSRVINSR', 'CSRVRTRN', 'CSRVSUM', 'CSRVDOC1', 'COLNTES1', 'CRVCLPAP', 'CRVCLHPV', 'CRVCLCNC', 'COLNSIGM', 'CASTHNO2', 'CSRVTRT3', 'HOWLONG', 'COLNCNCR', 'HADSIGM4', 'CSRVPAIN', 'HADHYST2', 'CERVSCRN', 'HADMAM', 'CNCRTYP1', 'CNCRAGE', 'CNCRDIFF', 'HAVEHEPB', 'TOLDHEPC', 'LCSNUMCG', 'LCSLAST', 'GUNLOAD', 'LCSFIRST', 'HPVADVC4', 'RSNMRJN2', 'USEMRJN3', 'SHINGLE2', 'TETANUS1', 'FEETCHK', 'DIABEDU', 'DIABEYE', 'EYEEXAM1', 'CHKHEMO3', 'DOCTDIAB', 'FEETCHK3', 'INSULIN1', 'BLDSUGAR', 'STOPSMK2', 'LCSCTSCN', 'FIREARM5', 'NUMPHON3', 'CIMEMLOS', 'CRGVALZD', 'DRADVISE', 'WTCHSALT', 'CRGVHOU1', 'CRGVPER1', 'CRGVPRB3', 'CRGVHRS1', 'CRGVLNG1', 'CRGVREL4', 'SHAREBP', 'WHEREBP', 'CAGEG', 'LANDSEX', 'LASTSMK2', 'CASTHDX2', 'RCSRLTN2', 'RCSGENDR', '_CLLCPWT', 'DIABAGE3', 'ACEADNED', 'ACEADSAF', 'ACEHVSEX', 'ACETTHEM', 'ACETOUCH', 'ACESWEAR', 'ACEHURT1', 'ACEPUNCH', 'ACEDIVRC', 'ACEPRISN', 'ACEDRUGS', 'ACEDRINK', 'ACEDEPRS', '_CPRACE1', '_CRACE1', 'ASTHNOW', 'RESPSLCT', 'NUMWOMEN', 'NUMMEN', 'PREGNANT', 'BIRTHSEX', 'SOMALE', 'PREDIAB1', 'PDIABTST', 'MSCODE', 'NUMADULT', 'NUMHHOL3', 'CTELENM1', 'STATERE1', 'LADULT1', 'CELPHON1', 'PVTRESD1', 'HOMRGCHK', 'HOMBPCHK', 'HIVTSTD3', 'SOFEMALE', 'MARIJAN1', 'JOINPAI2', 'ARTHDIS2', 'LMTJOIN3', 'ARTHEXER', 'ARTHEDU', 'CRGVEXPT', '_PNEUMO3', '_FLSHOT7', 'SMOKDAY2', 'BPMEDS', '_DUALCOR', 'CAREGIV1', 'IMFVPLA2', 'MAXDRNKS', 'DRNK3GE5', 'AVEDRNK3', 'FLSHTMY3', 'POORHLTH', 'TRNSGNDR', '_CHISPNC', 'CELLSEX', 'HHADULT', 'CTELNUM1', 'LANDLINE', 'SAFETIME', 'CELLFON5', 'CADULT1', 'PVTRESD3', 'CSTATE1']
Shape sebelum: (438693, 304)
Shape sesudah: (438693, 139)

In [15]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Columns: 139 entries, _STATE to CVD_LABEL
dtypes: float64(133), object(6)
memory usage: 465.2+ MB

In [16]:
# Cara 1 - Print list kolom yang dihapus
cols_to_drop = miss[miss >= 25].index
print(f"Kolom yang dihapus ({len(cols_to_drop)}):")
print(list(cols_to_drop))

Kolom yang dihapus (165):
['HAVECFS', 'WORKCFS', 'TOLDCFS', 'COLGHOUS', 'COLGSEX', 'SIGMTES1', 'MEDSHEPB', 'TRETHEPC', 'PRIRHEPC', 'HAVEHEPC', 'VCLNTES1', 'SDNATES1', 'BLDSTFIT', 'CSRVCTL2', 'LASTSIG4', 'PCSTALK', 'PCPSARS2', 'PSATIME1', 'STOLTEST', 'CCLGHOUS', 'CDHELP', 'STOOLDN1', 'VIRCOLO1', 'SMALSTOL', 'PSATEST1', 'HPVADSHT', 'CSRVINST', 'LOADULK2', 'CDDISCUS', 'CDSOCIAL', 'CDASSIST', 'CDHOUSE', 'CSRVCLIN', 'CSRVDEIN', 'CSRVINSR', 'CSRVRTRN', 'CSRVSUM', 'CSRVDOC1', 'COLNTES1', 'CRVCLPAP', 'CRVCLHPV', 'CRVCLCNC', 'COLNSIGM', 'CASTHNO2', 'CSRVTRT3', 'HOWLONG', 'COLNCNCR', 'HADSIGM4', 'CSRVPAIN', 'HADHYST2', 'CERVSCRN', 'HADMAM', 'CNCRTYP1', 'CNCRAGE', 'CNCRDIFF', 'HAVEHEPB', 'TOLDHEPC', 'LCSNUMCG', 'LCSLAST', 'GUNLOAD', 'LCSFIRST', 'HPVADVC4', 'RSNMRJN2', 'USEMRJN3', 'SHINGLE2', 'TETANUS1', 'FEETCHK', 'DIABEDU', 'DIABEYE', 'EYEEXAM1', 'CHKHEMO3', 'DOCTDIAB', 'FEETCHK3', 'INSULIN1', 'BLDSUGAR', 'STOPSMK2', 'LCSCTSCN', 'FIREARM5', 'NUMPHON3', 'CIMEMLOS', 'CRGVALZD', 'DRADVISE', 'WTCHSALT', 'CRGVHOU1', 'CRGVPER1', 'CRGVPRB3', 'CRGVHRS1', 'CRGVLNG1', 'CRGVREL4', 'SHAREBP', 'WHEREBP', 'CAGEG', 'LANDSEX', 'LASTSMK2', 'CASTHDX2', 'RCSRLTN2', 'RCSGENDR', '_CLLCPWT', 'DIABAGE3', 'ACEADNED', 'ACEADSAF', 'ACEHVSEX', 'ACETTHEM', 'ACETOUCH', 'ACESWEAR', 'ACEHURT1', 'ACEPUNCH', 'ACEDIVRC', 'ACEPRISN', 'ACEDRUGS', 'ACEDRINK', 'ACEDEPRS', '_CPRACE1', '_CRACE1', 'ASTHNOW', 'RESPSLCT', 'NUMWOMEN', 'NUMMEN', 'PREGNANT', 'BIRTHSEX', 'SOMALE', 'PREDIAB1', 'PDIABTST', 'MSCODE', 'NUMADULT', 'NUMHHOL3', 'CTELENM1', 'STATERE1', 'LADULT1', 'CELPHON1', 'PVTRESD1', 'HOMRGCHK', 'HOMBPCHK', 'HIVTSTD3', 'SOFEMALE', 'MARIJAN1', 'JOINPAI2', 'ARTHDIS2', 'LMTJOIN3', 'ARTHEXER', 'ARTHEDU', 'CRGVEXPT', '_PNEUMO3', '_FLSHOT7', 'SMOKDAY2', 'BPMEDS', '_DUALCOR', 'CAREGIV1', 'IMFVPLA2', 'MAXDRNKS', 'DRNK3GE5', 'AVEDRNK3', 'FLSHTMY3', 'POORHLTH', 'TRNSGNDR', '_CHISPNC', 'CELLSEX', 'HHADULT', 'CTELNUM1', 'LANDLINE', 'SAFETIME', 'CELLFON5', 'CADULT1', 'PVTRESD3', 'CSTATE1']

In [17]:
data1 = data1.drop(columns=['IDATE', 'IMONTH', 'IDAY', 'IYEAR','_STATE','FMONTH','DISPCODE','SEQNO','_PSU'])
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Columns: 130 entries, SEXVAR to CVD_LABEL
dtypes: float64(129), object(1)
memory usage: 435.1+ MB

In [18]:
# Cara 4 - Dalam bentuk DataFrame (paling mudah dibaca)
pd.DataFrame({
    'Kolom': data1.columns,
    'Tipe Data': data1.dtypes.values,
    'Missing (%)': (data1.isnull().mean() * 100).round(2).values
})

         Kolom Tipe Data  Missing (%)
0       SEXVAR   float64          0.0
1      GENHLTH   float64          0.0
2     PHYSHLTH   float64          0.0
3     MENTHLTH   float64          0.0
4     PRIMINSR   float64          0.0
..         ...       ...          ...
125    _FRT16A   float64          0.0
126    _VEG23A   float64          0.0
127   _FRUITE1   float64          0.0
128   _VEGETE1   float64          0.0
129  CVD_LABEL    object          0.0

[130 rows x 3 columns]

In [19]:
data1['CVD_LABEL'].value_counts()

CVD_LABEL
Healt                391852
Stroke Only           11518
CHD Only              11048
Heart Attack Only     10295
MI + CHD               8285
MI + Stroke            2137
All Three              2114
CHD + Stroke           1444
Name: count, dtype: int64

In [20]:
severity_map = {
    'Healt'            : 0,  # Sehat
    'Stroke Only'       : 1,  # Level 1 → 1 kondisi
    'CHD Only'          : 1,  # Level 1 → 1 kondisi
    'Heart Attack Only' : 1,  # Level 1 → 1 kondisi
    'MI + CHD'          : 2,  # Level 2 → 2 kondisi
    'MI + Stroke'       : 2,  # Level 2 → 2 kondisi
    'CHD + Stroke'      : 2,  # Level 2 → 2 kondisi
    'All Three'         : 3,  # Level 3 → 3 kondisi
}

data1['CVD_SEVERITY'] = data1['CVD_LABEL'].map(severity_map)

# Verifikasi
print(data1['CVD_SEVERITY'].value_counts())
print(f"\nTotal : {len(data1):,}")

CVD_SEVERITY
0    391852
1     32861
2     11866
3      2114
Name: count, dtype: int64

Total : 438,693

In [21]:
data1 = data1.drop(columns=['_VEGRES1','_FRTRES1','_MISVEG1','_MISFRT1','CVD_LABEL'])
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438693 entries, 0 to 438692
Columns: 126 entries, SEXVAR to CVD_SEVERITY
dtypes: float64(125), int64(1)
memory usage: 421.7 MB

In [22]:
# Cek null semua kolom
null_summary = pd.DataFrame({
    'null_count': data1.isnull().sum(),
    'null_percent': (data1.isnull().sum() / len(data1) * 100).round(2)
}).sort_values('null_percent', ascending=False)

print(null_summary[null_summary['null_count'] > 0])

          null_count  null_percent
CHOLMED3       61571         14.04
_RFCHOL3       61151         13.94
TOLDHI3        60836         13.87
_VEGESU1       60127         13.71
_FRUTSU1       51087         11.65
...              ...           ...
PHYSHLTH           3          0.00
HAVARTH5           3          0.00
EDUCA              5          0.00
RENTHOM1           8          0.00
GENHLTH            4          0.00

[75 rows x 2 columns]

In [23]:
data_new = data1.dropna()
print(f"Sebelum : {len(data1)} baris")
print(f"Sesudah : {len(data_new)} baris")
print(f"Terhapus: {len(data1) - len(data_new)} baris")

Sebelum : 438693 baris
Sesudah : 289586 baris
Terhapus: 149107 baris

In [24]:
data_new

,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,PRIMINSR,PERSDOC3,MEDCOST1,CHECKUP1,EXERANY2,BPHIGH6,...,VEGEDA2_,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1,CVD_SEVERITY
0,2.0,5.0,20.0,10.0,3.0,1.0,2.0,2.0,2.0,3.0,...,100.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
2,2.0,2.0,88.0,88.0,2.0,2.0,2.0,1.0,2.0,1.0,...,43.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,1
3,2.0,2.0,88.0,10.0,2.0,1.0,2.0,1.0,1.0,1.0,...,71.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
4,1.0,5.0,30.0,88.0,3.0,1.0,2.0,1.0,1.0,4.0,...,100.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2
5,1.0,3.0,88.0,88.0,3.0,1.0,2.0,1.0,2.0,3.0,...,14.0,29.0,42.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431633,2.0,3.0,88.0,88.0,88.0,3.0,2.0,4.0,2.0,2.0,...,100.0,29.0,200.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
431634,2.0,3.0,30.0,88.0,1.0,2.0,1.0,1.0,2.0,3.0,...,57.0,107.0,122.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
431635,1.0,3.0,88.0,88.0,1.0,1.0,2.0,2.0,1.0,3.0,...,100.0,16.0,257.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
431636,1.0,4.0,10.0,88.0,3.0,1.0,2.0,1.0,2.0,3.0,...,100.0,100.0,207.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0
431637,1.0,3.0,20.0,30.0,3.0,1.0,2.0,1.0,1.0,1.0,...,71.0,28.0,185.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,0

In [25]:
# Pastikan semua kolom ini tidak ada
forbidden = ['_MICHD', 'CVDSTRK3', 'CVDCRHD4', 'CVDINFR4']
data_new = data_new.drop(columns=forbidden)
for col in forbidden:
    if col in data_new.columns:
        print(f"⚠️  MASIH ADA: {col}")
    else:
        print(f"✅ Sudah dihapus: {col}")

✅ Sudah dihapus: _MICHD
✅ Sudah dihapus: CVDSTRK3
✅ Sudah dihapus: CVDCRHD4
✅ Sudah dihapus: CVDINFR4

In [26]:
data_new['CVD_SEVERITY'].value_counts()

CVD_SEVERITY
0    255497
1     23661
2      8870
3      1558
Name: count, dtype: int64

In [ ]:
# ============================================================
# SUBSAMPLE — ambil N baris random dari seluruh data
# ============================================================

# SAMPLE_SIZE = 50_000   # ← ganti sesuai kebutuhan

# data_sampled = data_new.sample(n=SAMPLE_SIZE, random_state=42)

# print("Distribusi setelah sampling:")
# print(data_sampled['CVD_SEVERITY'].value_counts().sort_index())

# # ── Split seperti biasa dari data yang sudah disubsample ────
# X = data_sampled.drop(columns=['CVD_SEVERITY'])
# y = data_sampled['CVD_SEVERITY']

Distribusi setelah sampling:
CVD_SEVERITY
0    44080
1     4092
2     1567
3      261
Name: count, dtype: int64

In [30]:
X = data_new.drop(columns=['CVD_SEVERITY'])
y = data_new['CVD_SEVERITY']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [32]:
from xgboost import XGBClassifier
import numpy as np
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.utils import resample
from sklearn.cluster import DBSCAN, KMeans
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE, ADASYN, BorderlineSMOTE,KMeansSMOTE
from imblearn.combine import SMOTETomek, SMOTEENN
from imblearn.over_sampling.base import BaseOverSampler
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [33]:
class DBSCANSMOTE(BaseOverSampler):
    """
    Menggunakan DBSCAN untuk memfilter data minoritas dari 'noise' (outlier).
    Setelah outlier dibuang, SMOTE diterapkan.
    """
    def __init__(self, eps=0.5, min_samples=5, random_state=None, **kwargs):
        super().__init__()
        self.eps = eps
        self.min_samples = min_samples
        self.random_state = random_state
        self.kwargs = kwargs

    def _fit_resample(self, X, y):
        target_stats = Counter(y)
        majority_class = max(target_stats, key=target_stats.get)

        X_clean, y_clean = [], []
        for c in target_stats.keys():
            mask = (y == c)
            Xc = X[mask]

            if c == majority_class or len(Xc) < self.min_samples:
                X_clean.append(Xc)
                y_clean.extend([c] * len(Xc))
            else:
                db = DBSCAN(eps=self.eps, min_samples=self.min_samples).fit(Xc)
                core_mask = db.labels_ != -1  # Membuang noise (label -1)

                if np.sum(core_mask) < 2:
                    core_mask = np.ones(len(Xc), dtype=bool)

                X_clean.append(Xc[core_mask])
                y_clean.extend([c] * np.sum(core_mask))

        if isinstance(X, pd.DataFrame):
            X_clean = pd.concat(X_clean, ignore_index=True)
        else:
            X_clean = np.vstack(X_clean)
        y_clean = np.array(y_clean)

        smote = SMOTE(random_state=self.random_state, **self.kwargs)
        return smote.fit_resample(X_clean, y_clean)

In [34]:
class DBSCANROS(BaseOverSampler):
    """
    Menggunakan DBSCAN untuk menghapus outlier dari kelas minoritas,
    kemudian melakukan Random Over Sampler (ROS) pada titik data intinya.
    """
    def __init__(self, eps=0.5, min_samples=5, random_state=None):
        super().__init__()
        self.eps = eps
        self.min_samples = min_samples
        self.random_state = random_state

    def _fit_resample(self, X, y):
        target_stats = Counter(y)
        majority_count = max(target_stats.values())

        X_res, y_res = [], []

        for c, count in target_stats.items():
            mask = (y == c)
            Xc = X[mask]

            if count == majority_count:
                X_res.append(Xc)
                y_res.extend([c] * count)
            else:
                if len(Xc) < self.min_samples:
                    X_oversampled = resample(Xc, replace=True, n_samples=majority_count, random_state=self.random_state)
                    X_res.append(X_oversampled)
                    y_res.extend([c] * majority_count)
                    continue

                db = DBSCAN(eps=self.eps, min_samples=self.min_samples).fit(Xc)
                core_mask = db.labels_ != -1

                if np.sum(core_mask) == 0:
                    core_mask = np.ones(len(Xc), dtype=bool)

                X_core = Xc[core_mask]
                X_oversampled = resample(X_core, replace=True, n_samples=majority_count, random_state=self.random_state)
                X_res.append(X_oversampled)
                y_res.extend([c] * majority_count)

        if isinstance(X, pd.DataFrame):
            X_res = pd.concat(X_res, ignore_index=True)
        else:
            X_res = np.vstack(X_res)
        return X_res, np.array(y_res)

In [35]:
class KMeansROS(BaseOverSampler):
    """
    Mengelompokkan data minoritas menjadi beberapa cluster menggunakan KMeans,
    lalu melakukan oversampling (ROS) secara seimbang pada setiap cluster.
    """
    def __init__(self, n_clusters=5, random_state=None):
        super().__init__()
        self.n_clusters = n_clusters
        self.random_state = random_state

    def _fit_resample(self, X, y):
        target_stats = Counter(y)
        majority_count = max(target_stats.values())

        X_res, y_res = [], []

        for c, count in target_stats.items():
            mask = (y == c)
            Xc = X[mask]

            if count == majority_count:
                X_res.append(Xc)
                y_res.extend([c] * count)
            else:
                n_clusters = min(self.n_clusters, len(Xc))
                if n_clusters > 1:
                    kmeans = KMeans(n_clusters=n_clusters, random_state=self.random_state, n_init=10).fit(Xc)
                    labels = kmeans.labels_
                else:
                    labels = np.zeros(len(Xc))

                samples_per_cluster = majority_count // n_clusters
                remainder = majority_count % n_clusters

                for i in range(n_clusters):
                    cluster_mask = (labels == i)
                    X_cluster = Xc[cluster_mask]
                    if len(X_cluster) == 0: continue

                    n_samples = samples_per_cluster + (1 if i < remainder else 0)
                    X_oversampled = resample(X_cluster, replace=True, n_samples=n_samples, random_state=self.random_state)
                    X_res.append(X_oversampled)
                    y_res.extend([c] * n_samples)

        if isinstance(X, pd.DataFrame):
            X_res = pd.concat(X_res, ignore_index=True)
        else:
            X_res = np.vstack(X_res)
        return X_res, np.array(y_res)

In [36]:
N_CLASSES    = 4
TOP_K        = 20
USE_FS       = True
TARGET_NAMES = ['0', '1', '2', '3']

SAMPLERS = {
    "raw"        : None,
    "smote"      : SMOTE(random_state=42),
    "adasyn"     : ADASYN(random_state=42),
    "bsmote"     : BorderlineSMOTE(kind='borderline-1', random_state=42),
    "smotetomek" : SMOTETomek(random_state=42),
    "smoteenn"   : SMOTEENN(random_state=42),
    # "kmeanssmote": KMeansSMOTE(random_state=42, cluster_balance_threshold=0.1),
    "dbscansmote": DBSCANSMOTE(random_state=42),
    # "kmeansros"  : KMeansROS(random_state=42),
    "dbscanros"  : DBSCANROS(random_state=42),
}

In [37]:
MODELS = {
    "Random Forest": RandomForestClassifier(
        n_estimators=300, max_depth=None, min_samples_split=2,
        min_samples_leaf=1, max_features="sqrt",
        class_weight="balanced", n_jobs=-1, random_state=42,
    ),
    "XGBoost": XGBClassifier(
        objective="multi:softprob", num_class=N_CLASSES,
        n_estimators=300, learning_rate=0.05, max_depth=6,
        subsample=0.8, colsample_bytree=0.8,
        eval_metric="mlogloss", random_state=42, verbosity=0,
    ),
    "LightGBM": LGBMClassifier(
        objective="multiclass", num_class=N_CLASSES,
        n_estimators=300, learning_rate=0.05,
        num_leaves=31, subsample=0.8, colsample_bytree=0.8,
        class_weight="balanced", n_jobs=-1, random_state=42, verbose=-1,
    ),
    "Extra Trees": ExtraTreesClassifier(
        n_estimators=300, max_depth=None, min_samples_split=2,
        min_samples_leaf=1, max_features="sqrt",
        class_weight="balanced", n_jobs=-1, random_state=42,
    ),
}

In [ ]:
# ============================================================
# LANGKAH 5: BPSO Feature Selection dengan XGBoost sebagai estimator
# ============================================================
import time
import numpy as np
from pyswarms.discrete import BinaryPSO
from sklearn.model_selection import cross_val_score
# --- Scaling (opsional tapi direkomendasikan) ---
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

N_CLASSES  = len(np.unique(y_train))
CV_FOLDS   = 3   # kurangi jika data besar supaya tidak terlalu lama

# ── Fungsi Objektif ──────────────────────────────────────────
def pso_objective_xgb(mask):
    """
    mask  : (n_particles, n_features) — nilai biner 0/1
    return: (n_particles,) — cost = 1 - accuracy (minimasi)
    """
    scores = []
    for i in range(mask.shape[0]):
        selected = np.where(mask[i] > 0.5)[0]

        # Jika tidak ada fitur terpilih → penalti maksimal
        if len(selected) == 0:
            scores.append(1.0)
            continue

        X_sel = X_train_scaled[:, selected]

        xgb = XGBClassifier(
            objective      = "multi:softprob",
            num_class      = N_CLASSES,
            n_estimators   = 100,          # lebih sedikit supaya cepat di PSO
            learning_rate  = 0.1,
            max_depth      = 4,
            subsample      = 0.8,
            colsample_bytree = 0.8,
            eval_metric    = "mlogloss",
            use_label_encoder = False,
            random_state   = 42,
            verbosity      = 0,
            n_jobs         = -1,
        )

        acc = cross_val_score(
            xgb,
            X_sel, y_train,
            cv      = CV_FOLDS,
            scoring = "accuracy",
            n_jobs  = -1,
        ).mean()

        scores.append(1.0 - acc)

    return np.array(scores)


# ── Jalankan BinaryPSO ───────────────────────────────────────
n_features = X_train_scaled.shape[1]

options = {
    'c1': 2.0,   # cognitive coefficient
    'c2': 2.0,   # social coefficient
    'w' : 0.9,   # inertia weight
    'k' : 10,    # jumlah tetangga (ring topology)
    'p' : 2,     # p-norm (2 = euclidean)
}

optimizer = BinaryPSO(
    n_particles = 30,
    dimensions  = n_features,
    options     = options,
)

print("\n" + "=" * 55)
print("BPSO FEATURE SELECTION (XGBoost Estimator)")
print("=" * 55)
print(f"Jumlah fitur     : {n_features}")
print(f"Jumlah partikel  : 30")
print(f"Iterasi          : 50")
print(f"CV folds         : {CV_FOLDS}")
print("Mulai optimisasi ...\n")

t0 = time.time()
# best_cost, best_mask = optimizer.optimize(pso_objective_xgb, iters=10) # bagian iterasi al
best_cost, best_mask = optimizer.optimize(pso_objective_xgb, iters=50) # bagian iterasi al
elapsed = time.time() - t0

selected_idx = np.where(best_mask > 0.5)[0]

# Terapkan ke data
X_train_pso = X_train_scaled[:, selected_idx]
X_test_pso  = X_test_scaled[:,  selected_idx]

# Nama fitur terpilih (jika X_train adalah DataFrame)
if hasattr(X_train, 'columns'):
    selected_features = X_train.columns[selected_idx].tolist()
    print(f"Fitur terpilih   : {selected_features}")
else:
    print(f"Indeks terpilih  : {selected_idx.tolist()}")

print(f"\nJumlah fitur terpilih : {len(selected_idx)} / {n_features}")
print(f"Best cost (1-acc)     : {best_cost:.4f}")
print(f"Estimated accuracy    : {(1 - best_cost) * 100:.2f}%")
print(f"Waktu PSO             : {elapsed:.1f} detik")
print(f"Shape X_train_pso     : {X_train_pso.shape}")
print(f"Shape X_test_pso      : {X_test_pso.shape}")

2026-04-03 05:09:11,518 - pyswarms.discrete.binary - INFO - Optimize for 10 iters with {'c1': 2.0, 'c2': 2.0, 'w': 0.9, 'k': 10, 'p': 2}

=======================================================
BPSO FEATURE SELECTION (XGBoost Estimator)
=======================================================
Jumlah fitur     : 121
Jumlah partikel  : 30
Iterasi          : 50
CV folds         : 3
Mulai optimisasi ...

pyswarms.discrete.binary: 100%|██████████|10/10, best_cost=0.118
2026-04-03 05:42:45,496 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 0.11752162542517874, best pos: [1 1 1 1 1 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1
 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1
 0 0 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 0 0 1 1
 0 1 1 1 1 0 1 0 0 1]

Fitur terpilih   : ['SEXVAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'PRIMINSR', 'BPHIGH6', 'CHOLCHK3', 'TOLDHI3', 'ASTHMA3', 'CHCSCNCR', 'ADDEPEV3', 'CHCKDNY2', 'VETERAN3', 'EMPLOY1', 'INCOME3', 'WEIGHT2', 'DEAF', 'BLIND', 'DECIDE', 'DIFFDRES', 'DIFFALON', 'SMOKE100', 'USENOW3', 'ALCDAY5', 'FLUSHOT7', 'HIVTST7', 'FRUIT2', 'FRUITJU2', 'FVGREEN1', 'FRENCHF1', 'VEGETAB2', 'QSTVER', 'QSTLANG', '_METSTAT', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_DUALUSE', '_LLCPWT2', '_LLCPWT', '_RFHLTH', '_PHYS14D', '_HLTHPLN', '_HCVU652', '_TOTINDA', '_RFHYPE6', '_CHOLCH3', '_CASTHM1', '_ASTHMS1', '_LMTWRK3', '_PRACE1', '_MRACE1', '_HISPANC', '_RACEG21', '_RACEGR3', '_AGEG5YR', '_AGE65YR', 'HTIN4', 'HTM4', 'WTKG3', '_BMI5', '_BMI5CAT', '_CHLDCNT', '_INCOMG1', '_SMOKER3', '_RFSMOK3', '_CURECI1', 'DRNKANY5', '_DRNKWK1', '_RFDRHV7', '_AIDTST4', 'GRENDA1_', 'FRNCHDA_', 'VEGEDA2_', '_FRUTSU1', '_VEGESU1', '_FRTLT1A', '_FRT16A', '_VEGETE1']

Jumlah fitur terpilih : 79 / 121
Best cost (1-acc)     : 0.1175
Estimated accuracy    : 88.25%
Waktu PSO             : 2014.0 detik
Shape X_train_pso     : (231668, 79)
Shape X_test_pso      : (57918, 79)

In [40]:
from imblearn.combine import SMOTEENN
from collections import Counter

# Target names sesuai label CVD_SEVERITY
TARGET_NAMES = ['0', '1', '2', '3']

# ── Helper: evaluate satu kombinasi sampler+model ────────────
def evaluate_one_pso(models, X_tr, y_tr, X_te, y_te, label, target_names=TARGET_NAMES):
    rows = []
    for name, model in models.items():
        print(f"   🔧 {name} | {label}")
        model.fit(X_tr, y_tr)
        y_pred  = model.predict(X_te)
        y_proba = model.predict_proba(X_te)

        acc = accuracy_score(y_te, y_pred)
        f1  = f1_score(y_te, y_pred, average='macro')
        auc = roc_auc_score(y_te, y_proba, multi_class='ovr', average='macro')
        cm  = confusion_matrix(y_te, y_pred)

        print(f"      ✅ Acc={acc:.4f}  F1={f1:.4f}  AUC={auc:.4f}")
        print(f"      CM:\n{cm}")
        print(classification_report(y_te, y_pred, target_names=target_names))

        rows.append({
            "Model"   : name,
            "Sampler" : label,
            "Accuracy": round(acc, 4),
            "F1-Score": round(f1,  4),
            "ROC-AUC" : round(auc, 4),
        })
    return pd.DataFrame(rows)


# ============================================================
# EKSPERIMEN 1 — RAW (tanpa resampling, fitur PSO)
# ============================================================
print("\n" + "=" * 60)
print("⚙️  SAMPLER: RAW | Fitur: PSO")
print("=" * 60)
print(f"Distribusi y_train : {sorted(Counter(y_train).items())}")

df_raw_pso = evaluate_one_pso(
    MODELS,
    X_train_pso, y_train,
    X_test_pso,  y_test,
    label="raw_pso"
)

df_raw_pso.to_csv("hasil_evaluasi_raw_pso.csv", index=False)
print("📁 Disimpan → hasil_evaluasi_raw_pso.csv")


# ============================================================
# EKSPERIMEN 2 — SMOTEENN (fitur PSO)
# ============================================================
print("\n" + "=" * 60)
print("⚙️  SAMPLER: SMOTEENN | Fitur: PSO")
print("=" * 60)

smoteenn = SMOTEENN(random_state=42)
X_train_smoteenn, y_train_smoteenn = smoteenn.fit_resample(X_train_pso, y_train)

print(f"Distribusi sebelum : {sorted(Counter(y_train).items())}")
print(f"Distribusi sesudah : {sorted(Counter(y_train_smoteenn).items())}")
print(f"Shape X_train      : {X_train_smoteenn.shape}")

df_smoteenn_pso = evaluate_one_pso(
    MODELS,
    X_train_smoteenn, y_train_smoteenn,
    X_test_pso,       y_test,
    label="smoteenn_pso"
)

df_smoteenn_pso.to_csv("hasil_evaluasi_smoteenn_pso.csv", index=False)
print("📁 Disimpan → hasil_evaluasi_smoteenn_pso.csv")


# ============================================================
# GABUNG DAN TAMPILKAN SEMUA HASIL
# ============================================================
df_all_pso = pd.concat([df_raw_pso, df_smoteenn_pso], ignore_index=True)
df_all_pso.to_csv("hasil_evaluasi_ALL_pso.csv", index=False)

print("\n" + "=" * 60)
print("📊 RINGKASAN HASIL (diurutkan F1-Score)")
print("=" * 60)
print(df_all_pso.sort_values("F1-Score", ascending=False).to_string(index=False))

============================================================
⚙️  SAMPLER: RAW | Fitur: PSO
============================================================
Distribusi y_train : [(0, 204397), (1, 18929), (2, 7096), (3, 1246)]
   🔧 Random Forest | raw_pso
      ✅ Acc=0.8823  F1=0.2344  AUC=0.8204
      CM:
[[51100     0     0     0]
 [ 4732     0     0     0]
 [ 1774     0     0     0]
 [  312     0     0     0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.00      0.00      0.00      4732
           2       0.00      0.00      0.00      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.88     57918
   macro avg       0.22      0.25      0.23     57918
weighted avg       0.78      0.88      0.83     57918

   🔧 XGBoost | raw_pso

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

      ✅ Acc=0.8822  F1=0.2484  AUC=0.8435
      CM:
[[51006    77    16     1]
 [ 4641    65    26     0]
 [ 1698    48    27     1]
 [  291    15     6     0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.32      0.01      0.03      4732
           2       0.36      0.02      0.03      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.88     57918
   macro avg       0.39      0.26      0.25     57918
weighted avg       0.82      0.88      0.83     57918

   🔧 LightGBM | raw_pso

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

      ✅ Acc=0.6662  F1=0.3180  AUC=0.8106
      CM:
[[35888 10120  4187   905]
 [ 1059  1981  1243   449]
 [  192   672   645   265]
 [   21    98   121    72]]
              precision    recall  f1-score   support

           0       0.97      0.70      0.81     51100
           1       0.15      0.42      0.23      4732
           2       0.10      0.36      0.16      1774
           3       0.04      0.23      0.07       312

    accuracy                           0.67     57918
   macro avg       0.32      0.43      0.32     57918
weighted avg       0.87      0.67      0.74     57918

   🔧 Extra Trees | raw_pso
      ✅ Acc=0.8823  F1=0.2362  AUC=0.8177
      CM:
[[51099     1     0     0]
 [ 4732     0     0     0]
 [ 1772     1     1     0]
 [  311     0     0     1]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.00      0.00      0.00      4732
           2       1.00      0.00      0.00      1774
           3       1.00      0.00      0.01       312

    accuracy                           0.88     57918
   macro avg       0.72      0.25      0.24     57918
weighted avg       0.81      0.88      0.83     57918

📁 Disimpan → hasil_evaluasi_raw_pso.csv

============================================================
⚙️  SAMPLER: SMOTEENN | Fitur: PSO
============================================================
Distribusi sebelum : [(0, 204397), (1, 18929), (2, 7096), (3, 1246)]
Distribusi sesudah : [(0, 111625), (1, 204284), (2, 204372), (3, 204397)]
Shape X_train      : (724678, 79)
   🔧 Random Forest | smoteenn_pso
      ✅ Acc=0.7310  F1=0.3140  AUC=0.8277
      CM:
[[39133 11714   253     0]
 [ 1501  3079   152     0]
 [  347  1301   126     0]
 [   35   246    30     1]]
              precision    recall  f1-score   support

           0       0.95      0.77      0.85     51100
           1       0.19      0.65      0.29      4732
           2       0.22      0.07      0.11      1774
           3       1.00      0.00      0.01       312

    accuracy                           0.73     57918
   macro avg       0.59      0.37      0.31     57918
weighted avg       0.87      0.73      0.78     57918

   🔧 XGBoost | smoteenn_pso
      ✅ Acc=0.7507  F1=0.3475  AUC=0.8263
      CM:
[[40681  8988  1322   109]
 [ 1733  2418   516    65]
 [  389   986   360    39]
 [   43   177    74    18]]
              precision    recall  f1-score   support

           0       0.95      0.80      0.87     51100
           1       0.19      0.51      0.28      4732
           2       0.16      0.20      0.18      1774
           3       0.08      0.06      0.07       312

    accuracy                           0.75     57918
   macro avg       0.34      0.39      0.35     57918
weighted avg       0.86      0.75      0.79     57918

   🔧 LightGBM | smoteenn_pso

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

      ✅ Acc=0.8039  F1=0.3461  AUC=0.8314
      CM:
[[44287  6107   669    37]
 [ 2360  2033   324    15]
 [  594   933   232    15]
 [   73   179    52     8]]
              precision    recall  f1-score   support

           0       0.94      0.87      0.90     51100
           1       0.22      0.43      0.29      4732
           2       0.18      0.13      0.15      1774
           3       0.11      0.03      0.04       312

    accuracy                           0.80     57918
   macro avg       0.36      0.36      0.35     57918
weighted avg       0.85      0.80      0.82     57918

   🔧 Extra Trees | smoteenn_pso
      ✅ Acc=0.7254  F1=0.3132  AUC=0.8218
      CM:
[[38823 11844   433     0]
 [ 1498  3046   188     0]
 [  350  1279   145     0]
 [   31   240    40     1]]
              precision    recall  f1-score   support

           0       0.95      0.76      0.85     51100
           1       0.19      0.64      0.29      4732
           2       0.18      0.08      0.11      1774
           3       1.00      0.00      0.01       312

    accuracy                           0.73     57918
   macro avg       0.58      0.37      0.31     57918
weighted avg       0.87      0.73      0.77     57918

📁 Disimpan → hasil_evaluasi_smoteenn_pso.csv

============================================================
📊 RINGKASAN HASIL (diurutkan F1-Score)
============================================================
        Model      Sampler  Accuracy  F1-Score  ROC-AUC
      XGBoost smoteenn_pso    0.7507    0.3475   0.8263
     LightGBM smoteenn_pso    0.8039    0.3461   0.8314
     LightGBM      raw_pso    0.6662    0.3180   0.8106
Random Forest smoteenn_pso    0.7310    0.3140   0.8277
  Extra Trees smoteenn_pso    0.7254    0.3132   0.8218
      XGBoost      raw_pso    0.8822    0.2484   0.8435
  Extra Trees      raw_pso    0.8823    0.2362   0.8177
Random Forest      raw_pso    0.8823    0.2344   0.8204

In [41]:
from imblearn.combine import SMOTETomek
from collections import Counter

# Target names sesuai label CVD_SEVERITY
TARGET_NAMES = ['0', '1', '2', '3']

# ── Helper: evaluate satu kombinasi sampler+model ────────────
def evaluate_one_pso(models, X_tr, y_tr, X_te, y_te, label, target_names=TARGET_NAMES):
    rows = []
    for name, model in models.items():
        print(f"   🔧 {name} | {label}")
        model.fit(X_tr, y_tr)
        y_pred  = model.predict(X_te)
        y_proba = model.predict_proba(X_te)

        acc = accuracy_score(y_te, y_pred)
        f1  = f1_score(y_te, y_pred, average='macro')
        auc = roc_auc_score(y_te, y_proba, multi_class='ovr', average='macro')
        cm  = confusion_matrix(y_te, y_pred)

        print(f"      ✅ Acc={acc:.4f}  F1={f1:.4f}  AUC={auc:.4f}")
        print(f"      CM:\n{cm}")
        print(classification_report(y_te, y_pred, target_names=target_names))

        rows.append({
            "Model"   : name,
            "Sampler" : label,
            "Accuracy": round(acc, 4),
            "F1-Score": round(f1,  4),
            "ROC-AUC" : round(auc, 4),
        })
    return pd.DataFrame(rows)


# ============================================================
# EKSPERIMEN 1 — RAW (tanpa resampling, fitur PSO)
# ============================================================
print("\n" + "=" * 60)
print("⚙️  SAMPLER: RAW | Fitur: PSO")
print("=" * 60)
print(f"Distribusi y_train : {sorted(Counter(y_train).items())}")

df_raw_pso = evaluate_one_pso(
    MODELS,
    X_train_pso, y_train,
    X_test_pso,  y_test,
    label="raw_pso"
)

df_raw_pso.to_csv("hasil_evaluasi_raw_pso.csv", index=False)
print("📁 Disimpan → hasil_evaluasi_raw_pso.csv")


# ============================================================
# EKSPERIMEN 2 — SMOTEENN (fitur PSO)
# ============================================================
print("\n" + "=" * 60)
print("⚙️  SAMPLER: SMOTEENN | Fitur: PSO")
print("=" * 60)

smotetomek = SMOTETomek(random_state=42)
X_train_smotetomek, y_train_smotetomek = smotetomek.fit_resample(X_train_pso, y_train)

print(f"Distribusi sebelum : {sorted(Counter(y_train).items())}")
print(f"Distribusi sesudah : {sorted(Counter(y_train_smoteenn).items())}")
print(f"Shape X_train      : {X_train_smoteenn.shape}")

df_smoteenn_pso = evaluate_one_pso(
    MODELS,
    X_train_smotetomek, y_train_smotetomek,
    X_test_pso,       y_test,
    label="smoteenn_pso"
)

df_smoteenn_pso.to_csv("hasil_evaluasi_smoteenn_pso.csv", index=False)
print("📁 Disimpan → hasil_evaluasi_smoteenn_pso.csv")


# ============================================================
# GABUNG DAN TAMPILKAN SEMUA HASIL
# ============================================================
df_all_pso = pd.concat([df_raw_pso, df_smoteenn_pso], ignore_index=True)
df_all_pso.to_csv("hasil_evaluasi_ALL_pso.csv", index=False)

print("\n" + "=" * 60)
print("📊 RINGKASAN HASIL (diurutkan F1-Score)")
print("=" * 60)
print(df_all_pso.sort_values("F1-Score", ascending=False).to_string(index=False))

============================================================
⚙️  SAMPLER: RAW | Fitur: PSO
============================================================
Distribusi y_train : [(0, 204397), (1, 18929), (2, 7096), (3, 1246)]
   🔧 Random Forest | raw_pso
      ✅ Acc=0.8823  F1=0.2344  AUC=0.8204
      CM:
[[51100     0     0     0]
 [ 4732     0     0     0]
 [ 1774     0     0     0]
 [  312     0     0     0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.00      0.00      0.00      4732
           2       0.00      0.00      0.00      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.88     57918
   macro avg       0.22      0.25      0.23     57918
weighted avg       0.78      0.88      0.83     57918

   🔧 XGBoost | raw_pso

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

      ✅ Acc=0.8822  F1=0.2484  AUC=0.8435
      CM:
[[51006    77    16     1]
 [ 4641    65    26     0]
 [ 1698    48    27     1]
 [  291    15     6     0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.32      0.01      0.03      4732
           2       0.36      0.02      0.03      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.88     57918
   macro avg       0.39      0.26      0.25     57918
weighted avg       0.82      0.88      0.83     57918

   🔧 LightGBM | raw_pso

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

      ✅ Acc=0.6662  F1=0.3180  AUC=0.8106
      CM:
[[35888 10120  4187   905]
 [ 1059  1981  1243   449]
 [  192   672   645   265]
 [   21    98   121    72]]
              precision    recall  f1-score   support

           0       0.97      0.70      0.81     51100
           1       0.15      0.42      0.23      4732
           2       0.10      0.36      0.16      1774
           3       0.04      0.23      0.07       312

    accuracy                           0.67     57918
   macro avg       0.32      0.43      0.32     57918
weighted avg       0.87      0.67      0.74     57918

   🔧 Extra Trees | raw_pso
      ✅ Acc=0.8823  F1=0.2362  AUC=0.8177
      CM:
[[51099     1     0     0]
 [ 4732     0     0     0]
 [ 1772     1     1     0]
 [  311     0     0     1]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.00      0.00      0.00      4732
           2       1.00      0.00      0.00      1774
           3       1.00      0.00      0.01       312

    accuracy                           0.88     57918
   macro avg       0.72      0.25      0.24     57918
weighted avg       0.81      0.88      0.83     57918

📁 Disimpan → hasil_evaluasi_raw_pso.csv

============================================================
⚙️  SAMPLER: SMOTEENN | Fitur: PSO
============================================================
Distribusi sebelum : [(0, 204397), (1, 18929), (2, 7096), (3, 1246)]
Distribusi sesudah : [(0, 111625), (1, 204284), (2, 204372), (3, 204397)]
Shape X_train      : (724678, 79)
   🔧 Random Forest | smoteenn_pso
      ✅ Acc=0.8695  F1=0.3043  AUC=0.8273
      CM:
[[49594  1294   212     0]
 [ 3945   657   130     0]
 [ 1295   368   111     0]
 [  195    86    31     0]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93     51100
           1       0.27      0.14      0.18      4732
           2       0.23      0.06      0.10      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.87     57918
   macro avg       0.35      0.29      0.30     57918
weighted avg       0.82      0.87      0.84     57918

   🔧 XGBoost | smoteenn_pso

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

      ✅ Acc=0.8801  F1=0.2778  AUC=0.8305
      CM:
[[50790   119   153    38]
 [ 4531    66   103    32]
 [ 1597    50   106    21]
 [  269     9    24    10]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94     51100
           1       0.27      0.01      0.03      4732
           2       0.27      0.06      0.10      1774
           3       0.10      0.03      0.05       312

    accuracy                           0.88     57918
   macro avg       0.38      0.27      0.28     57918
weighted avg       0.81      0.88      0.83     57918

   🔧 LightGBM | smoteenn_pso

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

      ✅ Acc=0.8812  F1=0.2587  AUC=0.8317
      CM:
[[50914   127    51     8]
 [ 4609    70    49     4]
 [ 1661    60    49     4]
 [  283    13    13     3]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     51100
           1       0.26      0.01      0.03      4732
           2       0.30      0.03      0.05      1774
           3       0.16      0.01      0.02       312

    accuracy                           0.88     57918
   macro avg       0.40      0.26      0.26     57918
weighted avg       0.81      0.88      0.83     57918

   🔧 Extra Trees | smoteenn_pso
      ✅ Acc=0.8759  F1=0.2818  AUC=0.8232
      CM:
[[50322   629   148     1]
 [ 4301   332    97     2]
 [ 1491   204    77     2]
 [  243    46    22     1]]
              precision    recall  f1-score   support

           0       0.89      0.98      0.94     51100
           1       0.27      0.07      0.11      4732
           2       0.22      0.04      0.07      1774
           3       0.17      0.00      0.01       312

    accuracy                           0.88     57918
   macro avg       0.39      0.28      0.28     57918
weighted avg       0.82      0.88      0.84     57918

📁 Disimpan → hasil_evaluasi_smoteenn_pso.csv

============================================================
📊 RINGKASAN HASIL (diurutkan F1-Score)
============================================================
        Model      Sampler  Accuracy  F1-Score  ROC-AUC
     LightGBM      raw_pso    0.6662    0.3180   0.8106
Random Forest smoteenn_pso    0.8695    0.3043   0.8273
  Extra Trees smoteenn_pso    0.8759    0.2818   0.8232
      XGBoost smoteenn_pso    0.8801    0.2778   0.8305
     LightGBM smoteenn_pso    0.8812    0.2587   0.8317
      XGBoost      raw_pso    0.8822    0.2484   0.8435
  Extra Trees      raw_pso    0.8823    0.2362   0.8177
Random Forest      raw_pso    0.8823    0.2344   0.8204

In [ ]:
def apply_feature_selection(X_train, X_test, y_train, top_k=TOP_K):
    print(f"\n📌 Feature Selection: memilih {top_k} fitur terbaik dengan XGBoost...")
    xgb_fs = XGBClassifier(n_estimators=100, random_state=42,
                            eval_metric='mlogloss', verbosity=0)
    xgb_fs.fit(X_train, y_train)

    feat_df = pd.DataFrame({
        'feature'   : X_train.columns if hasattr(X_train, 'columns') else [f"f{i}" for i in range(X_train.shape[1])],
        'importance': xgb_fs.feature_importances_,
    }).sort_values('importance', ascending=False)

    selected = feat_df.head(top_k)['feature'].tolist()
    print(f"   Top fitur: {selected[:5]} ... ({top_k} total)")

    if hasattr(X_train, 'columns'):
        return X_train[selected], X_test[selected]
    else:
        idx = feat_df.head(top_k).index.tolist()
        return np.array(X_train)[:, idx], np.array(X_test)[:, idx]

In [ ]:
def evaluate_one(models, X_tr, y_tr, X_te, y_te, label, target_names=TARGET_NAMES):
    rows = []
    for name, model in models.items():
        print(f"   🔧 {name} | {label}")
        model.fit(X_tr, y_tr)
        y_pred  = model.predict(X_te)
        y_proba = model.predict_proba(X_te)

        acc = accuracy_score(y_te, y_pred)
        f1  = f1_score(y_te, y_pred, average='macro')
        auc = roc_auc_score(y_te, y_proba, multi_class='ovr', average='macro')
        cm  = confusion_matrix(y_te, y_pred)

        print(f"      ✅ Acc={acc:.4f}  F1={f1:.4f}  AUC={auc:.4f}")
        print(f"      CM:\n{cm}")
        print(classification_report(y_te, y_pred, target_names=target_names))

        rows.append({
            "Model"   : name,
            "Dataset" : label,
            "Accuracy": round(acc, 4),
            "F1-Score": round(f1,  4),
            "ROC-AUC" : round(auc, 4),
        })
    return pd.DataFrame(rows)

In [ ]:
def run_pipeline(X_train, X_test, y_train, y_test,
                 models=MODELS, samplers=SAMPLERS,
                 use_fs=USE_FS, top_k=TOP_K):

    print("=" * 60)
    print("🚀 MEMULAI PIPELINE")
    print("=" * 60)

    # Feature selection
    if use_fs:
        X_tr_base, X_te_base = apply_feature_selection(X_train, X_test, y_train, top_k)
        fs_tag = "fs"
    else:
        X_tr_base, X_te_base = X_train, X_test
        fs_tag = "nonfs"

    all_results = []

    for sampler_name, sampler in samplers.items():
        label = f"{sampler_name}_{fs_tag}"
        print(f"\n{'─'*50}")
        print(f"⚙️  Sampler: {sampler_name.upper()} | FS: {use_fs}")

        # Balancing
        if sampler is None:
            X_tr, y_tr = X_tr_base, y_train
        else:
            X_tr, y_tr = sampler.fit_resample(X_tr_base, y_train)
            dist = sorted(Counter(y_tr).items())
            print(f"   Distribusi setelah resample: {dist}")

        # Train & evaluate
        df = evaluate_one(models, X_tr, y_tr, X_te_base, y_test, label)
        all_results.append(df)

        # Simpan CSV per sampler
        fname = f"hasil_evaluasi_{label}.csv"
        df.to_csv(fname, index=False)
        print(f"   📁 Disimpan → {fname}")

    # Gabung semua hasil
    final_df = pd.concat(all_results, ignore_index=True)
    final_df.to_csv("hasil_evaluasi_SEMUA.csv", index=False)

    print("\n" + "=" * 60)
    print("✅ PIPELINE SELESAI")
    print("=" * 60)
    print(final_df.sort_values("F1-Score", ascending=False).to_string(index=False))

    return final_df

In [ ]:
# Tanpa Feature Selection
results_nonfs = run_pipeline(X_train, X_test, y_train, y_test, use_fs=False)

============================================================
🚀 MEMULAI PIPELINE
============================================================

──────────────────────────────────────────────────
⚙️  Sampler: RAW | FS: False
   🔧 Random Forest | raw_nonfs
      ✅ Acc=0.8823  F1=0.2344  AUC=0.8401
      CM:
[[51100     0     0     0]
 [ 4732     0     0     0]
 [ 1774     0     0     0]
 [  312     0     0     0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.00      0.00      0.00      4732
           2       0.00      0.00      0.00      1774
           3       0.00      0.00      0.00       312

    accuracy                           0.88     57918
   macro avg       0.22      0.25      0.23     57918
weighted avg       0.78      0.88      0.83     57918

   🔧 XGBoost | raw_nonfs

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

      ✅ Acc=0.8820  F1=0.2601  AUC=0.8598
      CM:
[[50926   137    37     0]
 [ 4586   112    34     0]
 [ 1630   100    43     1]
 [  263    35    12     2]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     51100
           1       0.29      0.02      0.04      4732
           2       0.34      0.02      0.05      1774
           3       0.67      0.01      0.01       312

    accuracy                           0.88     57918
   macro avg       0.55      0.26      0.26     57918
weighted avg       0.82      0.88      0.83     57918

   🔧 LightGBM | raw_nonfs
      ✅ Acc=0.6860  F1=0.3292  AUC=0.8292
      CM:
[[36940  9760  3712   688]
 [ 1033  2047  1263   389]
 [  157   679   680   258]
 [   13   113   124    62]]
              precision    recall  f1-score   support

           0       0.97      0.72      0.83     51100
           1       0.16      0.43      0.24      4732
           2       0.12      0.38      0.18      1774
           3       0.04      0.20      0.07       312

    accuracy                           0.69     57918
   macro avg       0.32      0.43      0.33     57918
weighted avg       0.87      0.69      0.76     57918

   🔧 Extra Trees | raw_nonfs
      ✅ Acc=0.8823  F1=0.2366  AUC=0.8342
      CM:
[[51099     1     0     0]
 [ 4731     1     0     0]
 [ 1772     0     2     0]
 [  311     0     0     1]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     51100
           1       0.50      0.00      0.00      4732
           2       1.00      0.00      0.00      1774
           3       1.00      0.00      0.01       312

    accuracy                           0.88     57918
   macro avg       0.85      0.25      0.24     57918
weighted avg       0.86      0.88      0.83     57918

   📁 Disimpan → hasil_evaluasi_raw_nonfs.csv

──────────────────────────────────────────────────
⚙️  Sampler: SMOTE | FS: False
   Distribusi setelah resample: [(0, 204397), (1, 204397), (2, 204397), (3, 204397)]
   🔧 Random Forest | smote_nonfs
      ✅ Acc=0.8804  F1=0.2755  AUC=0.8430
      CM:
[[50676   345    79     0]
 [ 4418   245    69     0]
 [ 1517   188    69     0]
 [  243    49    19     1]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94     51100
           1       0.30      0.05      0.09      4732
           2       0.29      0.04      0.07      1774
           3       1.00      0.00      0.01       312

    accuracy                           0.88     57918
   macro avg       0.62      0.27      0.28     57918
weighted avg       0.82      0.88      0.84     57918

   🔧 XGBoost | smote_nonfs
      ✅ Acc=0.8810  F1=0.2707  AUC=0.8526
      CM:
[[50887    69   108    36]
 [ 4545    41   104    42]
 [ 1624    31    85    34]
 [  275     6    21    10]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     51100
           1       0.28      0.01      0.02      4732
           2       0.27      0.05      0.08      1774
           3       0.08      0.03      0.05       312

    accuracy                           0.88     57918
   macro avg       0.38      0.27      0.27     57918
weighted avg       0.81      0.88      0.83     57918

   🔧 LightGBM | smote_nonfs
      ✅ Acc=0.8811  F1=0.2676  AUC=0.8554
      CM:
[[50906    84    88    22]
 [ 4585    47    69    31]
 [ 1640    36    69    29]
 [  268     9    26     9]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     51100
           1       0.27      0.01      0.02      4732
           2       0.27      0.04      0.07      1774
           3       0.10      0.03      0.04       312

    accuracy                           0.88     57918
   macro avg       0.38      0.27      0.27     57918
weighted avg       0.81      0.88      0.83     57918

   🔧 Extra Trees | smote_nonfs
      ✅ Acc=0.8819  F1=0.2638  AUC=0.8397
      CM:
[[50888   162    50     0]
 [ 4557   130    44     1]
 [ 1625    91    58     0]
 [  274    23    14     1]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     51100
           1       0.32      0.03      0.05      4732
           2       0.35      0.03      0.06      1774
           3       0.50      0.00      0.01       312

    accuracy                           0.88     57918
   macro avg       0.51      0.26      0.26     57918
weighted avg       0.82      0.88      0.83     57918

   📁 Disimpan → hasil_evaluasi_smote_nonfs.csv

──────────────────────────────────────────────────
⚙️  Sampler: ADASYN | FS: False
   Distribusi setelah resample: [(0, 204397), (1, 208531), (2, 204749), (3, 204988)]
   🔧 Random Forest | adasyn_nonfs

In [ ]:
# Dengan Feature Selection
results_fs = run_pipeline(X_train, X_test, y_train, y_test, use_fs=True)